export default [
  { icon: 'mdi-view-dashboard', title: 'dashboard', to: '/' },
  { icon: 'mdi-application-cog', title: 'Master Outlet', to: '/master/outlet' },
  { icon: 'mdi-clipboard-account', title: 'Master Users', to: '/master/users' },
  { icon: 'mdi-account-cog', title: 'Master Roles', to: '/master/roles' },
  { icon: 'mdi-account-cog', title: 'Master Brand', to: '/master/brand' },
  { icon: 'mdi-account-cog', title: 'Master Region', to: '/master/region' },
  { icon: 'mdi-account-cog', title: 'Master Sio', to: '/master/sio' },
  { icon: 'mdi-account-cog', title: 'Master Batch', to: '/master/batch' },
  { icon: 'mdi-account-group', title: 'Call Plan', to: '/call-plan' },
  { title: 'rtables', icon: 'mdi-clipboard-outline', to: '/tables/regular-tables' },
  { title: 'typography', icon: 'mdi-format-font', to: '/components/typography' },
  { title: 'icons', icon: 'mdi-chart-bubble', to: '/components/icons' },
  { title: 'google', icon: 'mdi-map-marker', to: '/maps/google-maps' },
  { title: 'notifications', icon: 'mdi-bell', to: '/components/notifications' },
];
